### ISSUE TITLE
Domain records

### ISSUE THREAD

**Issue by z0ccc** [mdp/dns_leak_server#1]
Hi,
What domain records are needed to use this project?
Thanks

**Comment by mdp** [comment]
Sorry, this project is a bit old and poorly documented. A better example, along with DNS records is 
https://github.com/mdp/PlaneBoard

Basically, you need an NS record for your subdomain pointing to the nameserver, then an A record pointing the nameserver to an IP

Something like:

‘’’
leak		    IN	NS	  ns.foo.com.
ns	            IN	A	  123.45.67.89
‘’’

Which on foo.com would create a nameserver for leak.foo.com, and the authority for all *.leak.foo.com subdomains would go to ns.foo.com / 123.45.67.89. 

Hope this helps
